angular.module("app.controllers",[])
.controller("articleCtrl",["$scope","articleFac",function($scope,articleFac){
  $scope.data=articleFac.get();
  console.log($scope.data)
}])
.controller("projectCtrl",["$scope","projectFac",function($scope,projectFac){
  $scope.data=projectFac.get();
  console.log($scope.data)
}])